version: "3"
services:
  gcn_env:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]